/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleDexSol from "./Simple-dex.sol";
export type { simpleDexSol };
export type { TestERC20Token } from "./TestERC20Token";
