/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proposal from "./proposal";
export type { proposal };
import type * as simpleDex from "./simple-dex";
export type { simpleDex };
