/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleDexSol from "./Simple-dex.sol";
export { TestERC20Token__factory } from "./TestERC20Token__factory";
